import Foundation

// Exact text keys preserve the wording of saved historical snapshots.
// 使用完整原文作为查找键，保留已存历史快照的原始措辞。
enum EnglishText {
    static let stories: [String: String] = [
        "末班来信": "The Last Letter",
        "一封盖着明天邮戳的信，留住了今晚的末班车。": "A letter stamped tomorrow holds back tonight's last train.",
        "末班车离站前，你在空荡的候车室捡到一封信。信封上写着你的名字，邮戳却是明天。": "Before the last train leaves, you find a letter in the empty station. It bears your name, but tomorrow's postmark.",
        "拆开信封": "Open it",
        "寻找失主": "Find its owner",
        "信里写着：别让旧站的灯熄灭。窗外，一个熟悉的背影正在离开，你也听见站长喊你的名字。": "The letter says: Don't let the old station's lamp go out. Outside, a familiar figure walks away. You also hear the stationmaster calling your name.",
        "追上背影": "Follow him",
        "询问站长": "Ask the master",
        "列车员认出信封上的字迹，说写信的人每晚都来。站长保管着他的留言，那人此刻就在窗外。": "The conductor recognizes the handwriting: the sender comes here every night. The stationmaster keeps his messages, and the man is just outside now.",
        "找站长": "Find the master",
        "你追到旧站门口，那人正把钥匙交给管理员。看见信封，他停下脚步：你终于愿意来了吗？": "You catch up at the old station's door. The man is handing his keys to the caretaker. Seeing the envelope, he stops. 'Have you finally decided to come?'",
        "请他留下": "Ask him to stay",
        "问起那封信": "Ask about it",
        "站长拿出一叠未寄出的信。最上面一封写着：如果今晚等不到你，我就搭末班车去远方。": "The stationmaster brings out a stack of unsent letters. The top one reads: If you don't come tonight, I'll take the last train somewhere far away.",
        "去追列车": "Catch the train",
        "点亮旧灯": "Light the lamp",
        "旧灯亮起，朋友回过头来。列车还在等，他问你：今晚留下聊聊，还是把没说的话写给明天？": "The old lamp lights up, and your friend turns back. The train is still waiting. 'Stay and talk tonight, or write what we never said for tomorrow?'",
        "留在今晚": "Stay tonight",
        "寄往明天": "For Tomorrow",
        "朋友走向列车，临行前递来一张空白明信片：把想说的话写给明天吧。你也可以邀他回旧站坐坐。": "As your friend walks toward the train, he hands you a blank postcard. 'Write what you want to say for tomorrow.' You could also invite him back to sit at the station.",
        "写下约定": "Make a promise",
        "一起回去": "Go back together",
        "灯火重逢": "Reunited",
        "你们在旧站读完了那些信。朋友笑着承认，明天的邮戳是他盖错的。幸好重逢没有再迟一天。": "You finish reading those letters together in the old station. Smiling, your friend admits he stamped tomorrow's date by mistake. Luckily, your reunion wasn't another day late.",
        "你按信上明天的日期写下见面约定。朋友登车前笑了：邮戳虽然盖错，明天的约定可不能再错过。": "You write a promise to meet on the letter's date: tomorrow. Before boarding, your friend smiles. 'The postmark was a mistake, but we mustn't miss tomorrow's meeting.'",
        "借雨小店": "Borrowed Rain",
        "这家店不卖伞，只借出一场你需要的雨。": "This shop lends you the rain you need, not an umbrella.",
        "你躲进街角小店，柜台上摆着许多装雨的玻璃瓶。店主说，每人只能借一场雨，天亮前归还。": "You shelter in a corner shop. Glass bottles of rain line the counter. The owner says each person may borrow just one shower, to be returned before dawn.",
        "借细雨": "Borrow drizzle",
        "借骤雨": "Borrow a storm",
        "细雨落进掌心，发出旧钢琴的声音。店主说这来自一座废弃花园，那里曾经有个露天音乐会。": "Drizzle falls into your palm with the sound of an old piano. The owner says it comes from an abandoned garden, where an outdoor concert was once held.",
        "去找花园": "Find the garden",
        "问雨的主人": "Ask whose rain",
        "瓶里的骤雨忽然安静下来。标签写着一个陌生人的名字，背面却画着你小时候常去的花园。": "The bottled storm suddenly falls quiet. The label bears a stranger's name; on the back is a drawing of the garden you often visited as a child.",
        "花园里的琴已经生锈。守园人说，弹琴的女孩走后，花就不再开了，只有雨天还能听见旋律。": "The garden piano has rusted. The keeper says the flowers stopped blooming after the girl who played it left. Only on rainy days can her tune still be heard.",
        "让雨落下": "Release the rain",
        "寻找女孩": "Find the player",
        "店主拿出一张旧照片：女孩如今住在对街，不再弹琴。她以为，早就没有人记得那场音乐会。": "The owner shows an old photograph. The girl now lives across the street and no longer plays. She thinks nobody remembers that concert anymore.",
        "敲她的门": "Knock on her door",
        "带雨回花园": "Take rain there",
        "雨落在琴盖上，敲出熟悉的节拍。女孩循声来到花园，却停在门外，问你这里还有听众吗？": "Rain taps a familiar rhythm on the piano lid. Following the sound, the girl reaches the garden but stops outside the gate. 'Is there still an audience here?'",
        "为她鼓掌": "Applaud her",
        "陪她听雨": "Listen to rain",
        "女孩坐在窗边，轻轻哼起旧曲。她说手指已经不够灵活，但你可以把这段旋律带回花园。": "By her window, the girl softly hums the old song. Her fingers aren't nimble enough anymore, she says, but you can take this melody back to the garden.",
        "记下旋律": "Note the tune",
        "邀她同行": "Invite her along",
        "雨中返场": "An Encore",
        "女孩重新坐到琴前，街坊撑伞听完最后一曲。天亮前，你归还了空瓶。瓶底多了一阵掌声。": "The girl returns to the piano. Neighbors listen under umbrellas until the last note. Before dawn, you return the empty bottle. A burst of applause rests at its bottom.",
        "留住雨声": "Rain Remembered",
        "你将旋律记在花园门口，天亮前归还雨瓶。后来每逢下雨，总有人轻哼。女孩的歌没有被忘记。": "You write down the melody at the garden gate and return the rain bottle before dawn. Later, whenever it rains, someone hums it. Her song has not been forgotten.",
        "月亮邮差": "Moon Post",
        "今晚最后一封信，收件地址是已经拆掉的家。": "Tonight's last letter is addressed to a home that no longer stands.",
        "你是今晚的月亮邮差。最后一封信没有门牌，只写着：送给还在等我回家的人。天就快亮了。": "You are tonight's moon postman. The last letter has no street number, only: 'To the one still waiting for me to come home.' Dawn is approaching.",
        "沿旧街找": "Search old street",
        "询问信封": "Ask the envelope",
        "旧街只剩一面矮墙，墙角的小猫追着你的影子。它脖子上的铜牌，刻着信封里隐约透出的名字。": "Only a low wall remains of the old street. A cat at its corner chases your shadow. Its brass collar tag bears the name faintly visible inside the envelope.",
        "跟着小猫": "Follow the cat",
        "读出名字": "Say the name",
        "信封回答：我记得一碗热汤，却不记得路。远处的小猫突然抬头，像听见有人在叫它。": "The envelope answers: 'I remember a bowl of hot soup, but not the way.' A cat in the distance suddenly looks up, as though someone has called it.",
        "小猫带你来到新楼，老人每天都在门口放一碗水。她说，搬家以后，怕远行的人找不到这里。": "The cat leads you to a new building. An old woman puts a bowl of water outside every day. Since moving, she has feared that her traveler won't find her here.",
        "递上信封": "Hand her the letter",
        "问旧家的事": "Ask of her home",
        "念出名字后，矮墙映出从前的厨房。桌上留着一碗汤，你听见老人说：地址变了，家还在。": "When you speak the name, the low wall reflects the old kitchen. A bowl of soup waits on the table. You hear the woman say: 'The address changed. Home is still here.'",
        "记下新地址": "Note the address",
        "循着汤香走": "Follow the aroma",
        "你循着汤香走进新家，老人认出了信上的字。她迟迟没有拆信，问你能否先陪她把汤热一热？": "Following the soup's aroma, you enter her new home. She recognizes the handwriting but hesitates to open the letter. 'Will you help me warm the soup first?'",
        "陪她热汤": "Warm the soup",
        "先读来信": "Read the letter",
        "信封上浮现出新的门牌。窗口的老人向你招手，你还来得及敲门，也可以把信轻放在窗台。": "A new street number appears on the envelope. The woman waves from her window. There is still time to knock, or you can gently leave the letter on the sill.",
        "放到窗台": "Leave on the sill",
        "敲门进去": "Knock and enter",
        "一碗热汤": "Warm Soup",
        "你陪老人喝完热汤，她才慢慢展开信。天亮前，你终于懂得，邮差送到的不只是纸上的消息。": "Only after sharing the hot soup does she slowly unfold the letter. Before dawn, you finally understand that a postman delivers more than messages on paper.",
        "新的门牌": "A New Address",
        "晨光照亮信封上的新地址。老人读完信，把门牌擦得很亮。从此远行的人，再也不会找错家。": "Morning lights the new address on the envelope. After reading the letter, she polishes her door number until it shines. Her traveler will never mistake the way home again.",
        "海边电台": "Coastal Radio",
        "停播多年的电台，收到一条来自海上的点歌。": "A long-silent radio station receives a song request from the sea.",
        "你收拾停播的海边电台时，耳机里响起一个请求：能再放一遍那首歌吗？屏幕没有显示来电。": "While tidying the long-silent coastal radio station, you hear a request through the headphones: 'Could you play that song once more?' No incoming call appears on the screen.",
        "回应声音": "Answer the voice",
        "查看日志": "Read the log",
        "对方说自己正在返航，却认不出岸上的灯。你找到旧海图，图角记着一组早已停用的频率。": "The caller says they are sailing home but cannot recognize the shore lights. You find an old sea chart with a long-abandoned radio frequency written in its corner.",
        "调到旧频率": "Tune in",
        "询问船名": "Ask the boat name",
        "日志最后一页记着一艘失联的小船。旁边夹着点歌单，背面是一组旧频率和船长的签名。": "The log's last page names a boat that lost contact. A song request is tucked beside it; on its back are an old frequency and the captain's signature.",
        "查询船名": "Look up the boat",
        "旧频率里传来年轻船长的求援录音，结尾是一首断掉的歌。你可以播出这段声音，也可以补完那首歌。": "On the old frequency, you hear a recording of a young captain calling for help. It ends with an interrupted song. You can broadcast his voice, or finish that song.",
        "播出录音": "Air the recording",
        "补完那首歌": "Finish the song",
        "退休的守塔人认出船名，说船长已经平安归来。只是当年为他点歌的人，没听到那句谢谢。": "The retired lighthouse keeper recognizes the boat's name. Its captain came home safely, he says. But the person who requested a song for him never heard his thanks.",
        "请他来电台": "Invite the keeper",
        "播放那首歌": "Play the song",
        "广播惊动了守塔人，他赶到电台，说自己就是当年的船长。麦克风亮起来，他问：还有人在听吗？": "Your broadcast brings the keeper hurrying to the station. He says he was that captain. As the microphone lights up, he asks: 'Is anyone still listening?'",
        "打开话筒": "Switch on the mic",
        "先放音乐": "Play music first",
        "守塔人来到电台，认出那首歌，承认自己就是船长。此时点歌人打来电话：让我听完，也可以聊聊。": "The keeper arrives, recognizes the song, and admits he was the captain. Just then, the requester calls: 'Let me hear it through. Or we could talk.'",
        "让歌播完": "Let it finish",
        "把电话给他": "Pass him the call",
        "迟到的谢谢": "A Late Thank You",
        "船长对着话筒说出迟到多年的谢谢。电话那头笑了：我一直知道你会回来。港口的灯逐盏亮起。": "At the microphone, the captain gives his long-delayed thanks. A laugh comes down the line: 'I always knew you would return.' The harbor lights come on one by one.",
        "为你重播": "Played for You",
        "你让整首歌安静地播完。第二天，电台门口多了一盒旧磁带，上面写着：下次，也请为我点歌。": "You let the whole song play quietly to its end. The next day, a box of old tapes appears at the station door. A note says: 'Next time, please request a song for me too.'",
        "补云的人": "The Cloud Mender",
        "城市上空破了一个洞，修补材料只有两段回忆。": "A hole opens in the sky. Two memories could mend it.",
        "清晨，城市上空的云破了一个洞。补云师递给你针线：要用一段回忆作补丁，你愿意挑哪一段？": "At dawn, a hole opens in the clouds above the city. The cloud mender gives you a needle and thread: 'The patch needs a memory. Which one will you choose?'",
        "快乐的回忆": "A happy memory",
        "遗憾的回忆": "A regret",
        "你想起小时候放飞的风筝，线轴变成一团金线。补云师说，先找到风筝，或者问问等你的人。": "You remember the kite you flew as a child, and the spool becomes golden thread. The mender says to find the kite first, or ask the person waiting for you.",
        "追寻风筝": "Follow the kite",
        "寻找旧友": "Find your friend",
        "你想起一次没有说出口的道歉，掌心出现蓝线。旧友住在云洞另一边，一只风筝正朝那里飞。": "You remember an apology you never spoke, and blue thread appears in your palm. Your old friend lives beyond the hole in the clouds. A kite is flying that way.",
        "风筝挂在屋顶，尾巴上系着你和朋友写下的愿望。纸已经褪色，但约好一起旅行的字还很清楚。": "The kite is caught on a roof. Tied to its tail are wishes you and your friend wrote. The paper has faded, but your promise to travel together is still clear.",
        "取下愿望": "Take the wishes",
        "叫朋友来看": "Call your friend",
        "旧友拿出另一半线轴，说一直等你来取。你们都笑了，原来这些年，谁也没有真正忘记约定。": "Your old friend brings out the other half of the spool, saying it has been waiting for you. You both laugh. Neither of you has truly forgotten the promise all these years.",
        "约好出发": "Plan the trip",
        "一起补云": "Mend together",
        "你带着旧愿望与朋友会合，接好两段线。补云师问，要把愿望缝进天空，还是带着它重新出发？": "You reunite with your friend and your old wishes, joining the threads. The mender asks: 'Stitch the wishes into the sky, or take them with you and set out again?'",
        "缝进天空": "Stitch the sky",
        "带着出发": "Take them along",
        "朋友赶来帮你缝好云洞，随后背起行囊：要一起走完约好的旧路，还是先在云上留下见面的路标？": "Your friend rushes over to help mend the cloud, then shoulders a bag. 'Shall we finish our promised old route, or first leave a sign in the clouds where we can meet?'",
        "走完旧路": "Walk the route",
        "留下路标": "Leave a sign",
        "天空的路标": "A Sign in the Sky",
        "云上多了一只风筝的形状。你们约定每年在这里见面，抬头就能找到那段不再失约的时光。": "A kite's shape appears in the clouds. You promise to meet here every year. A glance upward will lead you to the memory of a promise no longer broken.",
        "重新出发": "Setting Out",
        "你把线轴装进行囊，和朋友走向车站。云洞被晨光轻轻补上，未完成的愿望终于有了下一页。": "You pack the spool and walk to the station with your friend. Morning light gently patches the cloud. The unfinished wish finally has a new page.",
        "你没有拆信。朋友接过完好的信封，说里面是给旧站的告别信。他愿意留下，或请你替他投递。": "You did not open the letter. Your friend takes the sealed envelope and says it holds his farewell to the old station. He is willing to stay, or let you post it for him.",
        "替他投递": "Post it for him",
        "朋友发现信封仍未拆开，便将旧站钥匙交给你：替我守住这间屋子，或者把告别信送出去吧。": "Seeing the envelope still sealed, your friend offers you the old station's keys: 'Keep this place for me, or send my farewell letter.'",
        "送出告别信": "Send his farewell",
        "接过钥匙": "Take the keys",
        "旧站守信人": "The Station Keeper",
        "你保留了信的秘密，也接过旧站的钥匙。朋友答应回来探望。从此灯亮起时，总有人在这里守候。": "You keep the letter's secret and accept the station keys. Your friend promises to visit. From now on, whenever the lamp is lit, someone will be waiting here.",
        "替你告别": "A Farewell Sent",
        "你把未拆的信投入邮筒。朋友终于安心离开。这一次，你没有替他决定去留，只替他完成了告别。": "You drop the unopened letter into the postbox. Your friend can finally leave at peace. You did not choose whether he stayed; you simply helped him say goodbye.",
        "你借来的骤雨冲开了琴底暗格，露出女孩藏下的手稿。她赶来问你：让旧曲响起，还是写一首新的？": "The storm you borrowed opens a hidden compartment beneath the piano, revealing the girl's lost score. She arrives and asks: 'Play the old piece, or write a new one?'",
        "演奏旧曲": "Play the old tune",
        "写首新曲": "Write a new one",
        "骤雨敲响窗沿，女孩翻出未完成的手稿。她想写进今天的雨声，也愿意为你再弹一遍旧日旋律。": "As the storm taps the windowsill, the girl brings out an unfinished score. She wants to write today's rain into it, but is also willing to play the old melody for you again.",
        "写进雨声": "Add today's rain",
        "重弹旧曲": "Replay the tune",
        "雨里的手稿": "The Lost Score",
        "骤雨替你找回了遗失的手稿。女孩照着旧谱弹完一曲，你归还雨瓶，把这段失而复得留在花园。": "The storm helped recover the lost score. The girl plays the old piece through. You return the rain bottle, leaving this rediscovery in the garden.",
        "新的雨季": "A New Rainy Season",
        "女孩把骤雨写进新曲，送你第一份乐谱。你准时还瓶，店主听见瓶里换了旋律，笑着收下它。": "The girl writes the storm into a new piece and gives you its first score. You return the bottle on time. Hearing its changed tune, the owner smiles and accepts it.",
        "一路与你说话的信封终于承认，它也害怕被读完。老人愿意把它留下作伴，或让你带它继续送信。": "The envelope that talked with you along the way admits it fears being finished and forgotten. The woman will keep it for company, or let you take it on more deliveries.",
        "留下作伴": "Let it stay",
        "带它同行": "Take it along",
        "信封把新门牌告诉你，却舍不得告别。老人读完信，问你能否带它看更多的家，或留在窗边陪她。": "The envelope gives you the new address but hates to say goodbye. After reading the letter, the woman asks you to show it more homes, or leave it by her window for company.",
        "带它旅行": "Travel together",
        "留在窗边": "Let it stay here",
        "会说话的家书": "A Letter's Home",
        "你从一开始就听见了信的心事。老人把它留在窗边，每晚和它说说话，远行的消息有了回声。": "From the start, you listened to the letter's wishes. The woman keeps it by her window and talks with it each night. Messages from far away now have an answering voice.",
        "邮差的伙伴": "A Postal Partner",
        "老人留下信纸，将会说话的信封交给你。下个夜晚，它坐在你的邮袋里，替你记住每一盏归家的灯。": "The woman keeps the letter and gives you the talking envelope. The next night it sits in your postbag, remembering every light that welcomes someone home.",
        "你先翻出的日志证明，那句求援曾被漏记。船长看着空白的一栏，请你公开补录，或亲手交还给他。": "The log you checked first proves the distress call was never recorded. Looking at the blank entry, the captain asks you to correct it publicly, or give him the log.",
        "公开补录": "Correct it on air",
        "交还日志": "Return the log",
        "歌声结束，船长问起你找到的日志。那页空白终于有了答案：你可以让他带走，也可以补入电台档案。": "When the song ends, the captain asks about the log you found. That blank page finally has an answer: let him take it away, or complete the station's archive.",
        "让他带走": "Let him keep it",
        "补入档案": "Complete the log",
        "补上的一页": "The Missing Entry",
        "你在直播里补录了当年的求援与归航。船长亲口签下名字。这座电台终于留下完整的记录。": "On air, you add the missing distress call and safe return to the record. The captain signs his own name. The radio station finally has the complete account.",
        "带回岸上": "Back Ashore",
        "你将日志交给船长，让他自己决定如何讲述往事。他抱着本子走出电台，这次没再回头寻找信号。": "You give the log to the captain, letting him decide how to tell his past. He leaves the station holding the book. This time, he doesn't look back for a signal.",
        "最初那段遗憾仍缠在线上。朋友听完你的道歉，愿意把结解开，也愿意把它留作不再失约的记号。": "The regret you chose still knots the thread. After hearing your apology, your friend is willing to untie it, or leave it as a sign never to break your promise again.",
        "解开线结": "Untie the knot",
        "留下记号": "Keep the reminder",
        "朋友指着蓝线上的结，说起那次没等到你的旅行。这一次，你可以留下结作提醒，或亲手把它解开。": "Your friend points to the knot in the blue thread and recalls the trip when you never arrived. This time, you can keep the knot as a reminder, or undo it yourself.",
        "留下线结": "Keep the knot",
        "亲手解开": "Undo it yourself",
        "解开的心结": "An Untied Knot",
        "你说完迟到的道歉，朋友握着你的手解开蓝线。云缝平整了，你们终于不用带着那次遗憾出发。": "You finish your long-delayed apology. Your friend holds your hand as you untie the blue thread. The cloud's seam lies flat; you can finally set out without that regret.",
        "不再失约": "A Promise Kept",
        "你们把线结留在云上，约好每次出发前都来看看。遗憾没有消失，却成了认真赴约的提醒。": "You leave the knot in the clouds and agree to visit it before every trip. The regret has not vanished, but it has become a reminder to honor your promises.",
        "雨夜失踪的曲谱": "The Missing Music",
        "茶馆打烊前，手写曲谱不见了。窗边水迹与一只蓝铁盒，谁能解释？": "A score vanishes before the tea shop closes. A wet sill and a blue tin may explain why.",
        "暴雨夜，茶馆的手写曲谱不见了。店主阿岚说送货员小周刚走，窗边还有水迹。你先查哪里？": "On a stormy night, the tea shop's handwritten score disappears. Lan, the owner, says courier Zhou just left. There is water by the window. Where do you investigate first?",
        "查看窗台": "Check the sill",
        "询问客人": "Ask a guest",
        "外窗台湿透，内侧积灰却没有脚印。曲谱原处留着一根蓝布线，柜台上恰有一块蓝布。": "The outer sill is soaked, but the dusty inner sill has no footprints. A blue thread lies where the score was. A piece of blue cloth sits on the counter.",
        "核对蓝布": "Match the cloth",
        "追问小周": "Question Zhou",
        "客人说小周离开时提着纸箱，却没看见曲谱。他还记得停电前，阿岚抱着蓝铁盒走向柜台。": "A guest saw Zhou leave with a carton, but did not see the score. Before the blackout, the guest also saw Lan carrying a blue tin toward the counter.",
        "检查铁盒": "Check the tin",
        "核对纸箱": "Check the carton",
        "布线与柜台蓝布的破口吻合。布下压着阿岚的便条：漏雨，曲谱移入蓝盒。柜台后有只蓝铁盒。": "The thread matches a tear in the blue cloth. Beneath it is Lan's note: 'Roof leaking. Score moved to blue tin.' A blue tin sits behind the counter.",
        "请她开盒": "Ask her to open it",
        "先指认小周": "Accuse Zhou",
        "小周说纸箱里是茶杯，愿意开箱。他记得阿岚说过屋顶漏雨，曾拿蓝布包起桌上一叠纸。": "Zhou says his carton holds teacups and offers to open it. He remembers Lan mentioning a roof leak and wrapping a stack of papers from the table in blue cloth.",
        "回店查蓝盒": "Return to the tin",
        "坚持查纸箱": "Check his carton",
        "铁盒旁有张阿岚署名的便条：漏雨，曲谱移入蓝盒。盒沿夹着蓝布，正是客人看见她抱走的那只。": "Beside the tin is a note signed by Lan: 'Roof leaking. Score moved to blue tin.' Blue cloth catches in its rim. It is the tin the guest saw her carry.",
        "小周当面打开纸箱，里面只有茶杯，送货单也对得上。他提醒你：阿岚收工前总会检查蓝铁盒。": "Zhou opens the carton in front of you. It holds only teacups, matching the delivery slip. He reminds you that Lan always checks the blue tin before closing.",
        "继续找赃物": "Keep searching",
        "阿岚打开蓝盒，曲谱果然裹在蓝布里。她想起停电时忙着接漏水，忘了搬动曲谱。你如何结案？": "Lan opens the blue tin. The score is there, wrapped in blue cloth. She remembers catching leaks during the blackout and forgetting she had moved it. How do you close the case?",
        "串起证据": "Explain the clues",
        "只报已找回": "Report it found",
        "回店后，阿岚按你的请求打开蓝盒，找到了曲谱。但是谁放进去、为什么放，你还没有核实。": "Back at the shop, Lan opens the blue tin at your request and finds the score. But you have not yet verified who put it there, or why.",
        "核实搬动原因": "Ask who and why",
        "你指认小周，他请你拿出证据。阿岚这时打开蓝盒，曲谱就在里面；她承认是自己避雨时收起的。": "You accuse Zhou, who asks for evidence. Just then, Lan opens the blue tin. The score is inside. She admits she put it there herself to protect it from the rain.",
        "向小周道歉": "Apologize to Zhou",
        "仍保留怀疑": "Stay suspicious",
        "纸箱没有曲谱，也没人见小周拿走它。蓝铁盒还没查过。阿岚问你，能认定是谁拿走了吗？": "The carton has no score, and nobody saw Zhou take it. You have not checked the blue tin yet. Lan asks whether you can say who took the score.",
        "暂不下结论": "Withhold judgment",
        "回店核实": "Go back and check",
        "阿岚取出曲谱，出示移入蓝盒的便条：停电时为避漏雨收起，忙乱中忘了。便条与实物相合，小周洗清嫌疑。": "Lan takes out the score and shows her note about moving it to the blue tin. She kept it dry during the blackout, then forgot in the rush. Note and object agree, clearing Zhou.",
        "蓝盒里的真相": "The Tin's Truth",
        "曲谱找回，演奏照常开始。你只报告物品平安，没有说明搬动经过。失物案结束了，小周却还等着一句澄清。": "The score is found and the performance begins on time. You report only that it is safe, not how it was moved. The lost item case is closed, but Zhou still awaits a word to clear his name.",
        "找回之后": "Found, Not Solved",
        "你撤回指认，向小周道歉。阿岚说明自己为避漏雨收起曲谱。小周接受了道歉：下次，先看证据再叫住我。": "You withdraw your accusation and apologize to Zhou. Lan explains that she put the score away to keep it dry. Zhou accepts: 'Next time, check the evidence before stopping me.'",
        "迟来的澄清": "A Late Apology",
        "你留下未结的调查记录。次日阿岚公布便条与蓝盒中的曲谱，证实只是避雨移放。没有证据，怀疑终究不是答案。": "You leave an unfinished case record. Next day, Lan shows her note and the score from the blue tin, proving she only moved it out of the rain. Without evidence, suspicion is no answer.",
        "未落笔的结论": "An Open Case",
        "优先未完成": "Unfinished first",
        "按列表顺序": "Library order",
        "暂时无法读取故事进度。原有数据已保留，请稍后重试。": "Unable to read your progress. Your saved data is safe. Please try again later.",
    ]
}

extension EnglishText {
    static let interface: [String: String] = [
        "四次选择，一段不同的故事。": "Four choices. A different story.",
        "在桌面读故事，在这里留下旅程。": "Read on your Home Screen. Keep your journeys here.",
        "正在桌面": "On your Home Screen",
        "已完成": "Completed",
        "回顾这段旅程": "Revisit this journey",
        "查看当前故事": "View current story",
        "故事书架": "Bookshelf",
        "正在读取故事…": "Loading stories…",
        "小小奇遇": "TinyStory",
        "故事库": "Library",
        "结局收藏": "Endings",
        "阅读概览": "Reading overview",
        "已探索分支图": "Explored branches",
        "我的旅程": "My Journeys",
        "阅读": "Reading",
        "换故事顺序": "Next story order",
        "桌面阅读指南": "Widget guide",
        "关于小小奇遇": "About TinyStory",
        "离线阅读 · 进度保存在本机": "Offline · Progress saved on this device",
        "不需要登录，也不需要联网。当前不提供云同步，删除 App 后数据可能无法恢复。": "No account or internet needed. Cloud sync is not available. Deleting the app may permanently remove your data.",
        "设置": "Settings",
        "读取未完成": "Unable to load",
        "重试": "Try again",
        "查看本轮剧情路径": "View current path",
        "已在桌面，返回小组件继续": "On your Home Screen. Continue in the widget.",
        "桌面正在显示这个结局": "The widget is showing this ending.",
        "在桌面显示结局": "Show ending in widget",
        "重新开始": "Restart",
        "探索与回顾": "Explore and revisit",
        "本轮继续旧版剧情；重新开始后进入新版分支，旧旅程和结局会保留。": "This run uses the original edition. Restart to play the new branches. Past journeys and endings will be kept.",
        "读到故事结尾后，会将结局收藏在这里。": "Finish a story to collect its ending here.",
        "重新开始这篇故事？": "Restart this story?",
        "取消": "Cancel",
        "本轮路径将存入历史旅程，已收藏的结局会保留。桌面将切换到这篇故事。": "Your current path will be saved in your journey history. Collected endings will stay. The widget will switch to this story.",
        "本轮剧情路径": "Current path",
        "旅程回顾": "Journey review",
        "这是根据升级时保留的选择记录恢复的路径，使用旧版剧情文本；更早已重玩的记录无法补回。": "This path was reconstructed from choices saved during an upgrade, using the original text. Earlier runs that were already erased cannot be recovered.",
        "读到这里": "You reached here",
        "读到结局时自动保存；中途重新开始也会保留已走路径。历史旅程保留当时的正文和选择。": "Completed stories are saved automatically. Restarting also saves your unfinished path. History keeps the text and choices from that run.",
        "还没有历史旅程。完成故事或重新开始后，可以在这里回顾。": "No past journeys yet. Complete a story or restart to revisit your path here.",
        "未完成的旅程": "An unfinished journey",
        "历史旅程": "Past journeys",
        "橙色连接表示走过的选择。未探索节点不显示剧情和结局名称。相同节点可能由不同路线到达。": "Orange links mark choices you have made. Unexplored scenes and ending names stay hidden. Different paths may reach the same scene.",
        "故事开始": "Story begins",
        "未探索": "Unexplored",
        "尚未发现结局": "No endings discovered yet",
        "结局": "Ending",
        "桌面阅读": "Widget reading",
        "优先未完成：按目录寻找尚未读完的故事，接着原进度读。按列表顺序：直接进入下一篇。遇到已完成故事会重新开始，已收藏结局保留。": "Unfinished first: continue the next unfinished story in library order. Library order: go straight to the next story. Completed stories restart, keeping collected endings.",
        "外观": "Appearance",
        "按钮保持橙色，App 外观跟随系统。": "Buttons stay orange. The app follows your system appearance.",
        "本地保存": "Local storage",
        "设置与进度只保存在这台设备。切换故事不会清空其他故事进度。": "Settings and progress stay on this device. Switching stories keeps each story's progress.",
        "阅读设置": "Reading settings",
        "添加小组件": "Add a widget",
        "1. 回到主屏幕，长按空白处。": "1. On your Home Screen, touch and hold an empty area.",
        "2. 点击「编辑」→「添加小组件」。": "2. Tap Edit, then Add Widget.",
        "3. 搜索「小小奇遇」，添加中号小组件。": "3. Search for TinyStory (小小奇遇 on a Chinese system) and add the medium widget.",
        "开始阅读": "Start reading",
        "在故事详情中选择要在桌面阅读的故事。返回主屏幕，点击 A 或 B，四次选择后获得结局。结局页可直接点「重新开始」或「换个故事」，无需打开 App。「换个故事」默认优先继续尚未完成的故事；也可在阅读设置中改为按列表顺序。遇到已完成故事会重新开始，收藏不丢失。切换故事会保留各自进度，所有小组件显示同一篇当前故事。": "Choose a story in its detail page. On your Home Screen, tap A or B to reach an ending in four choices. Restart or choose Next story right in the widget. By default, Next story continues an unfinished story; you can change this in Reading settings. Completed stories restart without losing endings. Each story keeps its progress, and all widgets show the same active story.",
        "进度与隐私": "Progress and privacy",
        "故事和进度均保存在本机，不需要联网。重新开始会保留已发现结局和历史旅程。当前不提供云同步或备份，删除 App 后数据可能无法恢复。": "Stories and progress stay on your device. No internet is needed. Restarting keeps discovered endings and past journeys. Cloud sync and backups are not available; deleting the app may permanently remove your data.",
        "换个故事": "Next story",
        "跟随系统": "Follow system",
        "简体中文": "简体中文",
        "语言": "Language",
        "语言同时应用于 App 和小组件，不改变故事进度。": "Language applies to the app and widget without changing your progress.",
        "上一页": "Previous",
        "下一页": "Next page",
        "暂时无法读取进度，请在 App 中重试。": "Unable to load progress. Please try again in the app.",
        "正文分页不计入剧情选择，请读完后选择 A/B。": "Pages do not count as story choices. Read to the last page to choose A or B.",
    ]
}
